In [15]:
import mxnet as mx
from mxnet import nd, autograd

In [16]:
x = nd.arange(12)

In [17]:
X = x.reshape(3, 4)
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [18]:
nd.dot(X, Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [19]:
nd.concat(X, Y, dim = 0), nd.concat(X, Y, dim = 1)

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  1.  4.  3.]
  [ 1.  2.  3.  4.]
  [ 4.  3.  2.  1.]]
 <NDArray 6x4 @cpu(0)>,
 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
  [ 4.  5.  6.  7.  1.  2.  3.  4.]
  [ 8.  9. 10. 11.  4.  3.  2.  1.]]
 <NDArray 3x8 @cpu(0)>)

In [20]:
X == Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [21]:
X.norm().asscalar()

22.494442

In [22]:
before = id(Y)
Y = X  + Y
id(Y) == before

False

In [23]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = Y
id(Z) == before

True

In [24]:
import numpy as np

P = np.ones((2, 3))
D = nd.array(P)
D.asnumpy(  )

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [25]:
x = nd.arange(4).reshape((4,1))

In [26]:
x.attach_grad()        

In [27]:
with autograd.record():
    y = 2 * nd.dot(x.T, x)

In [28]:
y.backward()

In [30]:
assert (x.grad - 4 * x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [31]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True


In [ ]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [34]:
a = nd.random.normal(shape = 1)
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()

In [35]:
a.grad == c / a


[1.]
<NDArray 1 @cpu(0)>

In [37]:
dir(nd.random)

['NDArray',
 '_Null',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_internal',
 '_random_helper',
 'current_context',
 'exponential',
 'exponential_like',
 'gamma',
 'gamma_like',
 'generalized_negative_binomial',
 'generalized_negative_binomial_like',
 'multinomial',
 'negative_binomial',
 'negative_binomial_like',
 'normal',
 'normal_like',
 'numeric_types',
 'poisson',
 'poisson_like',
 'randint',
 'randn',
 'shuffle',
 'uniform',
 'uniform_like']

In [38]:
help(nd.ones_like)

Help on function ones_like:

ones_like(data=None, out=None, name=None, **kwargs)
    Return an array of ones with the same shape and type
    as the input array.
    
    Examples::
    
      x = [[ 0.,  0.,  0.],
           [ 0.,  0.,  0.]]
    
      ones_like(x) = [[ 1.,  1.,  1.],
                      [ 1.,  1.,  1.]]
    
    
    
    Parameters
    ----------
    data : NDArray
        The input
    
    out : NDArray, optional
        The output NDArray to hold the result.
    
    Returns
    -------
    out : NDArray or list of NDArrays
        The output of this function.

