## 1.多输入通道

In [15]:
import d2lzh as d2l
from mxnet import nd

def corr2d_multi_in(X, K):
    return nd.add_n(*[d2l.corr2d(x, k) for x, k in zip(X, K)])


In [16]:
X = nd.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
K = nd.array([[[0, 1], [2, 3]], [[1, 2], [3, 4]]])

corr2d_multi_in(X, K)


[[ 56.  72.]
 [104. 120.]]
<NDArray 2x2 @cpu(0)>

## 2.多输出通道

In [17]:
def corr2d_multi_in_out(X, K):
    return nd.stack(*[corr2d_multi_in(X, k) for k in K])

In [18]:
K = nd.stack(K, K + 1, K + 2)
K.shape

(3, 2, 2, 2)

In [19]:
corr2d_multi_in_out(X, K)


[[[ 56.  72.]
  [104. 120.]]

 [[ 76. 100.]
  [148. 172.]]

 [[ 96. 128.]
  [192. 224.]]]
<NDArray 3x2x2 @cpu(0)>

## 3. 1×1卷积层

In [20]:
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h * w))
    K = K.reshape((c_o, c_i))
    Y = nd.dot(K, X)
    return Y.reshape((c_o, h, w))



In [21]:
x = nd.random.uniform(shape = (3, 3, 3))
K = nd.random.uniform(shape = (2, 3, 1, 1))

Y1 = corr2d_multi_in_out_1x1(x, K)
Y2 = corr2d_multi_in_out(x, K)

(Y1 - Y2).norm().asscalar() < 1e-6

True