## 2.从零开始实现

In [15]:
import d2lzh as d2l
from mxnet import autograd, nd, init, gluon
from mxnet.gluon import loss as gloss, nn
import collections

def dropout(X, drop_prob):
    assert 0 <= drop_prob <= 1
    keep_prob = 1 - drop_prob
    # 这种情况下把全部元素都丢弃
    if keep_prob == 0:
        return X.zeros_like()
    mask = nd.random.uniform(0, 1, X.shape) < keep_prob
    return mask * X / keep_prob

In [13]:
X = nd.arange(16).reshape((2, 8))
dropout(X, 0)


[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]]
<NDArray 2x8 @cpu(0)>

In [14]:
dropout(X, 0.5)


[[ 0.  0.  4.  0.  8.  0. 12. 14.]
 [16. 18.  0.  0. 24. 26. 28.  0.]]
<NDArray 2x8 @cpu(0)>

In [15]:
dropout(X, 1)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
<NDArray 2x8 @cpu(0)>

In [16]:
# 定于模型参数
num_inputs, num_outputs, num_hiddens1, num_hiddens2 = 784, 10, 256, 256
W1 = nd.random.normal(scale = 0.01, shape = (num_inputs, num_hiddens1))
b1 = nd.zeros(num_hiddens1)
W2 = nd.random.normal(scale = 0.01, shape = (num_hiddens1, num_hiddens2))
b2 = nd.zeros(num_hiddens2)
W3 = nd.random.normal(scale = 0.01, shape = (num_hiddens2, num_outputs))
b3 = nd.zeros(num_outputs)

params = [W1, b1, W2, b2, W3, b3]
for param in params:
    param.attach_grad()

In [17]:
#定义模型
drop_prob1, drop_prob2 = 0.2, 0.5

def net(X):
    X = X.reshape((-1, num_inputs))
    H1 = (nd.dot(X, W1) + b1).relu()
    if autograd.is_training():
        H1 = dropout(H1, drop_prob1)
    H2 = (nd.dot(H1, W2) + b2).relu()
    if autograd.is_training():
        H2 = dropout(H2, drop_prob2)
    return nd.dot(H2, W3) + b3

In [18]:
# 训练和测试模型
num_epochs, lr, batch_size = 5, 0.5, 256
loss = gloss.SoftmaxCrossEntropyLoss()
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)
d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, params, lr)

epoch 1, loss 1.1395, train acc 0.564, test acc 0.788
epoch 2, loss 0.5766, train acc 0.786, test acc 0.840
epoch 3, loss 0.4971, train acc 0.819, test acc 0.845
epoch 4, loss 0.4511, train acc 0.837, test acc 0.863
epoch 5, loss 0.4225, train acc 0.846, test acc 0.863


## 3.简洁实现

In [19]:
net = nn.Sequential()
net.add(nn.Dense(256, activation = 'relu'),
        nn.Dropout(drop_prob1),
        nn.Dense(256, activation = 'relu'),
        nn.Dropout(drop_prob2),
        nn.Dense(10))
net.initialize(init.Normal(sigma = 0.01))

In [20]:
trainer = gluon.Trainer(net.collect_params(), 'sgd', {'learning_rate': lr})
d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size, None, None, trainer)

epoch 1, loss 1.1080, train acc 0.569, test acc 0.792
epoch 2, loss 0.5738, train acc 0.787, test acc 0.837
epoch 3, loss 0.4832, train acc 0.825, test acc 0.845
epoch 4, loss 0.4449, train acc 0.839, test acc 0.867
epoch 5, loss 0.4131, train acc 0.850, test acc 0.867


In [9]:
s = 'abc'
def abc():
    return ""
abc()
for i in s:
    print(i)

a
b
c


In [ ]:
def minWindow(self, s: str, t: str) -> str:
        need=collections.defaultdict(int)
        for c in t:
            need[c]+=1
        needCnt=len(t)
        i=0
        res=(0,float('inf'))
        for j,c in enumerate(s):
            if need[c]>0:
                needCnt-=1
            need[c]-=1
            if needCnt==0:       #步骤一：滑动窗口包含了所有T元素
                while True:      #步骤二：增加i，排除多余元素
                    c=s[i] 
                    if need[c]==0:
                        break
                    need[c]+=1
                    i+=1
                if j-i<res[1]-res[0]:   #记录结果
                    res=(i,j)
                need[s[i]]+=1  #步骤三：i增加一个位置，寻找新的满足条件滑动窗口
                needCnt+=1
                i+=1
        return '' if res[1]>len(s) else s[res[0]:res[1]+1]    #如果res始终没被更新过，代表无满足条件的结果
minWindow(1,'ADOBECODEBANC','ABC')

defaultdict(<class 'int'>, {'A': 1, 'B': 1, 'C': 1})
3
(0, inf)


'BANC'

In [22]:
def lengthOfLongestSubstring(self, s):
    """
        :type s: str
        :rtype: int
    """
    need = collections.defaultdict(int)
    maxlen = 1
    chong = 0
    havechong = 0
    i = 0
    for j, c in enumerate(s):
        
        need[c] += 1
        if need[c] > 1:
            chong = 1
        if chong > 0 and need[c] > 1:
            if j - i > maxlen:
                maxlen = j - i
            while i < j:
                c = s[i]
                i += 1
                need[c] -= 1
                if need[c] == 1:
                    chong = 0
                    break
        if havechong == 0:
            maxlen = j + 1 - i
    return 0 if len(s) == 0 else maxlen
lengthOfLongestSubstring(1, "aab")

2

In [ ]:
class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:
        if not s:return 0
        left = 0
        lookup = set()
        n = len(s)
        max_len = 0
        cur_len = 0
        for i in range(n):
            cur_len += 1
            while s[i] in lookup:
                lookup.remove(s[left])
                left += 1
                cur_len -= 1
            if cur_len > max_len:max_len = cur_len
            lookup.add(s[i])
        return max_len
